title: Denying Wifi Access - By Diego Contreras
description: Someone hogging your wifi? Absolutely detest someone? Fear no more; Nemesis is here.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
